FACE_VECTOR_PATH = 'output/out_visage_instagram.json'
MAXIMUM_EPOCHS = 1000
LOG_RESULTS = True
NUMBER_TRIALS = 100
BATCH_SIZE = 64
NUM_WORKERS = 8
API_KEY = "eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vdWkubmVwdHVuZS5haSIsImFwaV91cmwiOiJodHRwczovL3VpLm5lcHR1bmUuYWkiLCJhcGlfa2V5IjoiMGI5ZDUwYzMtNDAxOS00N2NmLWEyZWMtNDRjZTlhYjMzZDQ4In0="